language: php
dist: trusty
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
matrix:
  include:
    - php: "5.3"
      dist: precise
git:
  depth: 3
cache:
  directories:
    - $HOME/pecl_cache
addons:
  apt:
    packages:
      - libyaml-dev
before_install:
  - git clone --depth=1 https://github.com/indeyets/syck.git && cd syck && ./bootstrap && ./configure && make && sudo make install
# no need to provide coverage more than once and no need for the speedbump otherwise
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]]; then phpenv config-rm xdebug.ini || true ; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then composer require codacy/coverage:dev-master ; fi
# no need to test formatting more than once and php_codesniffer does not work with older php
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.2" ]]; then composer remove --dev squizlabs/php_codesniffer ; fi
# preparing cache
  - composer require phwoolcon/ci-pecl-cacher
install:
# installing composer
  - composer update
# installing syck
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "5" ]]; then vendor/bin/ci-pecl-install syck-0.9.3 || true ; fi
# installing yaml
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then vendor/bin/ci-pecl-install yaml-2.0.2 || true ; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:1} == "5" ]]; then vendor/bin/ci-pecl-install yaml-1.3.1 || true ; fi
script:
# unit tests
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "7.1" ]]; then phpunit --testdox --bootstrap vendor/autoload.php test/; fi
# check standards
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then vendor/bin/phpcs -p --standard=PSR2 src test ; fi
# unit tests + coverage
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then phpunit --testdox --coverage-text --coverage-clover build/logs/clover.xml --bootstrap vendor/autoload.php --whitelist src/ test/ && vendor/bin/codacycoverage clover build/logs/clover.xml ; fi
